---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sync
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-sync
rules:
  - apiGroups:
      - ''
      - 'homerow.ca'
    resources:
      - 'secret'
      - 'SyncSecret'
    verbs:
      - get
      - watch
      - list
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-sync
subjects:
  - kind: ServiceAccount
    name: secret-sync
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
