name: build-push
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - '**/README.md'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start a local k3s cluster
        uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: latest

      - name: 'Get app version'
        run: 'cp ~/.kube/config .'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Get app version'
        id: app-version
        run: |
          VERSION="$(grep '^version =' Cargo.toml | cut -d'"' -f2)"
          echo "app_version=$VERSION" >> "$GITHUB_OUTPUT"

      - uses: tyriis/docker-image-tag-exists@v2.1.0
        id: image-exists
        with:
          registry: ghcr.io
          repository: mulan-szechuan-sauce/sercet-sync
          tag: "${{ steps.app-version.outputs.app_version }}"

      - uses: docker/build-push-action@v6
        name: 'Build and push docker container'
        with:
          context: .
          push: ${{ (steps.image-exists.outputs.tag == 'found') && 'false' || 'true' }}
          tags: ghcr.io/mulan-szechuan-sauce/sercet-sync:latest,ghcr.io/mulan-szechuan-sauce/sercet-sync:${{ steps.app-version.outputs.app_version }}
          network: host
